export const SET_LOADING = 'SET_LOADING';
export const RESET_LOADING = 'RESET_LOADING';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const GET_PICTURES_SUCCESS = 'GET_PICTURES_SUCCESS';
